// <auto-generated />
namespace ServiceShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addRateTemptoemployeemodeltoholdtemporaryRatevaluebeforeconcattoRatingData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addRateTemptoemployeemodeltoholdtemporaryRatevaluebeforeconcattoRatingData));
        
        string IMigrationMetadata.Id
        {
            get { return "201811261419160_add RateTemp to employee model to hold temporary Rate value before concat to RatingData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
