// <auto-generated />
namespace ServiceShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Enableroles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Enableroles));
        
        string IMigrationMetadata.Id
        {
            get { return "201811180006046_Enable roles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
